services:
  # Backend Server
  - type: web
    name: project-ap-server
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: CLIENT_URL
        sync: false # You'll set this manually after frontend is deployed

  # Frontend Static Site
  - type: web
    name: project-ap-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SERVER_URL
        sync: false # You'll set this manually after backend is deployed
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
